kind: ConfigMap
apiVersion: v1
metadata:
  name: wao-scheduler-config
  namespace: kube-system
data:
  policy.cfg: |
    {
        "kind" : "Policy",
        "apiVersion" : "v1",
        "metadata" : {
            "name": "wao-scheduler-config",
            "namespace": "kube-system"
        },
        "predicates" : [
            {"name" : "PodFitsResources"},
            {"name" : "PodFitsHostPorts"},
            {"name" : "NoDiskConflict"},
            {"name" : "NoVolumeZoneConflict"},
            {"name" : "PodToleratesNodeTaints"},
            {"name" : "MatchInterPodAffinity"}
        ],
        "priorities" : [
            {"name" : "LeastRequestedPriority", "weight" : 1},
            {"name" : "BalancedResourceAllocation", "weight" : 1},
            {"name" : "ServiceSpreadingPriority", "weight" : 1},
            {"name" : "EqualPriority", "weight" : 1},
            {"name" : "MostRequestedPriority", "weight" : 10}
        ],
        "extenders": [
           {
               "urlPrefix": "http://127.0.0.1:8100",
               "apiVersion": "v1",
               "filterVerb": "filter",
               "enableHttps": false
           }
        ]
     }
